name: arp-scanner # you probably want to 'snapcraft register <name>'
version: "0.2.0.0" # just for humans, typically '1.2+git' or '1.3.2'
grade: devel # must be 'stable' to release into candidate/stable channels
summary: A lightweight cross-platform IP scanner # 79 char long summary
description: |
  A lightweight cross-platform IP scanner

base: core22 # the base snap is the execution environment for this snap

architectures:
  - build-on: amd64
  - build-on: arm64

confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  whatime:
    # See 'snapcraft plugins'
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    source: .
    build-packages:
      - dotnet-sdk-6.0
    stage-packages:
      - libicu70

apps:
  whatime:
    command: arp-scanner
