name: arp-scanner # you probably want to 'snapcraft register <name>'
version: "1.0.0.0" # just for humans, typically '1.2+git' or '1.3.2'
grade: stable # must be 'stable' to release into candidate/stable channels
summary: A lightweight cross-platform IP scanner # 79 char long summary
description: |
  **Usage**

  1. Download the latest release
  - Chocolatey (Windows): `choco install arp-scanner`
  - Snapcraft (Linux): `snap install arp-scanner`
  - GitHub (Windows/Linux): https://github.com/Stone-Red-Code/ARP-Scanner/releases
  1. Start `arp-scanner` with the IP range it should scan as parameter (e.g. `192.168.1.0 - 192.168.1.255`)

  > Note: This programm may not work on all linux distributions because the [ArpLookup](https://github.com/georg-jung/ArpLookup) library has some [limitations](https://github.com/georg-jung/ArpLookup#supported-platforms)

  **Third party licenses**
  - ArpLookup (https://github.com/georg-jung/ArpLookup) - MIT (https://github.com/georg-jung/ArpLookup/blob/master/LICENSE.txt)
  - IPAddressRange (https://github.com/jsakamoto/ipaddressrange) - MPL-2.0 (https://github.com/jsakamoto/ipaddressrange/blob/master/LICENSE)

base: core24 # the base snap is the execution environment for this snap

architectures:
  - build-on: amd64
  - build-on: arm64

confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  arp-scanner:
    # See 'snapcraft plugins'
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    source: ./src/ARP-Scanner
    build-packages:
      - dotnet-sdk-8.0
    stage-packages:
      - libicu70

apps:
  arp-scanner:
    command: ARP-Scanner
    plugs:
      - network-observe
